### ISSUE TITLE
Use pre-commit for velox4j's spotless check

### ISSUE THREAD

**Issue by assignUser** [facebookincubator/velox#13802]
### Description

Once #13186 is merged we can add spotless as a pre-commit check. Something like this should work:
```Dockerfile
FROM maven:3.9.6-eclipse-temurin-17 AS build

ADD java/velox4j/ .

# Get dependencies
RUN mvn spotless:check

# Final stage with just the installed dependencies
FROM maven:3.9.6-eclipse-temurin-17

# Copy the .m2 folder from the build stage
COPY --from=build /root/.m2 /root/.m2
```
and the hook
```yaml
- id: java-spotless
        name: java-spotless
        description: Apply maven spotless fixes.
        language: docker_image
        types: [java]
        pass_filenames: false
        entry: >
          --workdir /src/java/velox4j
          -u root
          velox_spotless
        args: [mvn, spotless:apply]
```
